### ISSUE TITLE
最新代码同步链数据panic

### ISSUE THREAD

**Issue by kaigedong** [DeepBrainChain/DeepBrainChain-MainChain#77]
仓库runtime version应在链上版本升级后进行升级。否则当同步链数据时，同步到链当前runtime版本，将会使用naive编译的binary.

**Comment by kaigedong** [comment]
2023-02-14 09:55:13 ✨ Imported #1791452 (0xbf28…8d50)
Hash: given=1ca1d6b38a9ba077ea298b3158ed15e965c43e9e33812a70c3f63b274e8e4518, expected=e99be4da59b7808a2cb7da502020d2f05d27039ef560b2e03de6cded53f70dec

====================

Version: 2.0.0-eff0b13-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/cfa3fe5af339e724209b25715282adae0c61628f/library/std/src/panicking.rs:610:17
   2: std::panicking::begin_panic::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: std::panicking::begin_panic
   5: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules,COnRuntimeUpgrade>::execute_block
   6: <node_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::
unchecked_extrinsic::UncheckedExtrinsic<sp_runtime::multiaddress::MultiAddress<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountI
d,u32>,node_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<node_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersi
on<node_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<node_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<node_runtime::Runtime>,frame_system
::extensions::check_nonce::CheckNonce<node_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<node_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<node_ru
ntime::Runtime>)>>>>::execute_block
   7: std::panicking::try
   8: std::thread::local::LocalKey<T>::with
   9: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
  10: sc_executor::wasm_runtime::RuntimeCache::with_instance
  11: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
  12: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
  13: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
  14: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
  15: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
  16: sp_api::runtime_decl_for_Core::execute_block_call_api_at
  17: sp_api::Core::execute_block_with_context
  18: <&sc_service::client::client::Client<B,E,Block,RA> as sp_consensus::block_import::BlockImport<Block>>::import_block
  19: <sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sp_consensus::block_import::BlockImport<Block>>::import_block
  20: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sp_consensus::block_import::BlockImport<Block>>::import_block
  21: <alloc::boxed::Box<dyn sp_consensus::block_import::BlockImport<B>+Transaction = Transaction+Error = sp_consensus::error::Error+core::marker::Sync+core::marker::Send> as sp_consensus::block_i
mport::BlockImport<B>>::import_block
  22: sp_consensus::import_queue::import_single_block_metered
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  25: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  26: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  27: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  28: <sc_service::task_manager::WithTelemetrySpan<T> as core::future::future::Future>::poll
  29: std::thread::local::LocalKey<T>::with
  30: futures_executor::local_pool::block_on
  31: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  32: tokio::runtime::task::core::Core<T,S>::poll
  33: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  34: tokio::runtime::task::harness::Harness<T,S>::poll
  35: tokio::runtime::blocking::pool::Inner::run
  36: tokio::runtime::context::enter
  37: std::sys_common::backtrace::__rust_begin_short_backtrace
  38: core::ops::function::FnOnce::call_once{{vtable.shim}}
  39: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/cfa3fe5af339e724209b25715282adae0c61628f/library/alloc/src/boxed.rs:1811:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/cfa3fe5af339e724209b25715282adae0c61628f/library/alloc/src/boxed.rs:1811:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/cfa3fe5af339e724209b25715282adae0c61628f/library/std/src/sys/unix/thread.rs:108:17
  40: <unknown>
  41: <unknown>


Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /home/bobo/.cargo/git/checkouts/substrate-7e08433d4c370a21/49a4103/frame/executive/src/lib.rs:405

This is a bug. Please report it at:

        https://github.com/paritytech/substrate/issues/new
